### ISSUE TITLE
Typo in README.rst

### ISSUE THREAD

**Issue by eric-solomon-esotech** [Martlark/flask-ipban#10]
A fork and pull request seems a little extreme for just 3 characters.

Line 129 of README.rst (https://github.com/Martlark/flask-ipban/blob/master/README.rst#methods)
`ip_ban.whitelist_add('127.0.0.1')`

This should actually be...
`ip_ban.ip_whitelist_add('127.0.0.1')`

This little difference was throwing me off pretty badly when learning how to use this plugin.

**Comment by Martlark** [comment]
Thanks for the notice.  I'll fix it up very soon.

**Comment by Martlark** [comment]
Typo fixed.
