### ISSUE TITLE
report_dir / record_dir inconsistency

### ISSUE THREAD

**Issue by boompig** [Martlark/flask-ipban#13]
Hi,

I believe the [current documentation](https://pypi.org/project/flask-ipban/) is not in sync with the code. In the documentation, the constructor accepts a parameter `report_dir`. However the causes an error during use. The source mentions `record_dir` which seems to be the same idea under a different name in [this file](https://github.com/Martlark/flask-ipban/blob/master/flask_ipban/ip_ban.py#L50). If I'm right, then a simple fix to the README should resolve this.

**Comment by Martlark** [comment]
I'll fix that.  Thanks for letting me know.
