### ISSUE TITLE
[feature request] ban findtime for n retries in a time period as ban_findtime parameter

### ISSUE THREAD

**Issue by akhiljalagam** [Martlark/flask-ipban#2]
**ban_findtime** sets the window that it will pay attention to when looking for repeated failed authentication attempts. Which means that the ipban will count the number of failed attempts in the last 10 minutes

**Comment by Martlark** [comment]
Are you requesting a feature to count the number of failed authentication requests?  I believe that's a feature that is better implemented in the host website and not in ipban.

**Comment by akhiljalagam** [comment]
![image](https://user-images.githubusercontent.com/21128035/70684851-99a7b600-1ccd-11ea-8c7f-c8e2493b49fc.png)

that is what missing.
findtime... means the number of failed authentication requests in a time period.
example:
findtime = 600
ban_count = 3

> will ban a client that unsuccessfully attempts to log in 3 times within a 10 minute window.

**Comment by Martlark** [comment]
I don't really see how ip ban can achieve this without significant interference in the host application.
