### ISSUE TITLE
limit the access of same ip after posting 5 requests

### ISSUE THREAD

**Issue by mohsin-noor** [Martlark/flask-ipban#21]
I was trying to develop a web app in python(flask) and I want to limit the access of this app (using ipban) flask-ipban with the user, each user can post 5 requests daily after certain time. for example: if the user post a request and submit, then the IP of the user will be blocked for few minutes and gets restored or unban when the ban seconds are over, and each IP can post upto 5 requests daily after certain amount of time. and if the limit of count is hit, i.e. 5 for one ip then the users ip should be blocked for 24 hours. 
I am unable to manage this situation to post limited requests and restore it after specific time and post upto 5 requests for individual user, daily. can you help me in this situation

**Comment by Martlark** [comment]
Let me think on this.

**Comment by BigweldIndustries** [comment]
update us when you can
