### ISSUE TITLE
This package is unable to uninstall...

### ISSUE THREAD

**Issue by JustAnEric** [Martlark/flask-ipban#22]
Hello coders,
<img width="249" alt="Screen Shot 2022-07-12 at 7 55 41 am" src="https://user-images.githubusercontent.com/73326807/178365511-e34076d1-5df0-4224-99d8-144bd391ac2c.png">
<img width="437" alt="Screen Shot 2022-07-12 at 7 55 25 am" src="https://user-images.githubusercontent.com/73326807/178365523-bbfff108-a222-4ae4-a607-9a19341844b0.png">
these keep popping up in my code after the uninstall process with pip. I am **very angry** now because I can't remove them. Also this too...
<img width="449" alt="Screen Shot 2022-07-12 at 7 59 45 am" src="https://user-images.githubusercontent.com/73326807/178366101-17b1eacb-7289-46c1-bb31-775c78f9c435.png">
Worst package i've ever seen.
Something ive also noticed worse enough is that the package sends a message in the console saying "read-only" or something along those lines. THIS IS A STUPID PACKAGE AND MY HOURS WORTH OF WORK GOT A PAY OF $2. NOW MY WEBSITE ISN'T UPDATING. WTF BRO

**Comment by JustAnEric** [comment]
total waste of time and bad support. idiots

**Comment by Martlark** [comment]
I'm sorry you are having issues.  Looks like your pip is having issues.  Also remove 'from flask_ipban...' if you are not using it and it's not installed.

**Comment by yoni13** [comment]
@WWEMGamer2 I think it's replit's problem,change to other platform bro
