### ISSUE TITLE
Can CIDR be used for IP?

### ISSUE THREAD

**Issue by bkaathi** [Martlark/flask-ipban#4]
Can CIDR or regex be used to ban IP address?

any_ip = "0.0.0.0/0"
app = Flask(__name__)
ip_ban = IpBan(app)
ip_ban.block(any_ip)

**Comment by Martlark** [comment]
That is not supported.  I presume you'd like to ban regions or organisations in bulk?

**Comment by Martlark** [comment]
I've added block_cidr method which provides this feature in release 1.1.0
