### ISSUE TITLE
How to specify the time between requests for the same ip address 

### ISSUE THREAD

**Issue by djamelsbar** [Martlark/flask-ipban#5]
ban_count  by default is 20 requetes, but what's the duration between these requests and how to specify this duration

**Comment by OneVoltTen** [comment]
From reading the code:
Function 'periodupdates' runs at 2*ban_seconds (default 1 day) then removes all entries that are in the list.
If you want to manually add a failed attempt (e.g. failed login) use `ip_ban.add()`.
20 failed results in 24 hour block (default).
How to specify this duration:
ip_ban = IpBan(app,  ban_seconds=3600 * 24) # this is the default value (1 day)

**Comment by Martlark** [comment]
@OneVoltTen correct.  Specify the ban time by using `ban_seconds` parameter when initializing.
