### ISSUE TITLE
20 attempt by default, what's duration between these 20 attempts

### ISSUE THREAD

**Issue by AdlanKadri** [Martlark/flask-ipban#7]
how to block IP address if i receive like more than 20 requests per second to detect it as a robot (spider), and please if you can give us an idea about behaviors which you considered as an attempt (because if i put iban_count = 20 that's mean after 20 attempts I'll block the IP address, but if this IP address does 20 attempts in 20 days (1 attempt/day) that kind of behavior is considered as a robot? ).

**Comment by Martlark** [comment]
Only requests that result in a 404, page not found, are counted in the default 20 requests limit.  The assumption is that this amount of not found pages is consistent with a vulnerability scanner or hacker probing your site.  Pages that are correctly handled by your site are not counted.  Care must be taken to cater for the increasing number of "meta" pages that google and other spiders are using to index your site.

**Comment by Martlark** [comment]
@AdlanKadri The default is to expire any record older than a day.  If the spider only accesses once a day, then it is likely that the ip  record won't ever reach the 20 requests minimum to trigger a ban.
